config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'

  
  get 'about' => 'pages#about'

  get 'team' => 'pages#team'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	#attr_accessor :image_file_name
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def team
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # Create = new  + create
  # Read/show = show
  # update =  edit + update
  # destroy = destroy


  
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at Desc").paginate(:page => params[:page], :per_page => 15)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params )

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Unauthorized to edit" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <%= link_to "Pinterest", root_path , class: "navbar-brand" %>
		      <!-- <a class="navbar-brand" href="#">Pinterest</a> -->
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      
		     
		      <ul class="nav navbar-nav navbar-right">
		        <li><%= link_to "Home",root_path%></li>
		        <li><%= link_to "About us",about_path%></li>
		        <% if user_signed_in? %>
					<li><%= link_to raw('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New'), new_pin_path %></li>
		        	<li><%= link_to "Account",edit_user_registration_path %></li>
		        	<li><%= link_to "Log out" , destroy_user_session_path, method: :delete %></li>
		        <% end %>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Pinterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>	
	<div class="container">
    <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<strong><h2 class="white-text">Pinterest</h2></strong>
		<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default" %> 
		<%= link_to "Sign up" , new_user_registration_path, class: "btn btn-success"  %>
		</p>
	
</div>

app/views/pages/about.html.erb
<div class="container center" style="max-width:500px">
	<h1>About us</h1>
	<p> We are working our one month rails app </p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my App</h1>
	<p>
	<%= link_to "Log in","#", class: "btn btn-default" , data: { toggle: 'modal', target: ".bs-example-modal-sm" }%> 
	<%= link_to "Sign up" , "new_user_registration_path" , class: "btn btn-warning"  %></p>
</div>



<!-- <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="center login">
      		<h2><b>Login in</b></h2>
      		<div class="form-group">
		    	<label for="username">username</label>
		    	<input type="email" class="form-control" id="loginusername" placeholder="username">
		  	</div>
			<div class="form-group">
			    <label for="password">Password</label>
			    <input type="password" class="form-control" id="loginpassword" placeholder="Password">
			</div>
			<div class="loginButton">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        		<button type="button" class="btn btn-primary">Save changes</button>
			</div>
      </div>
    </div>
  </div>
</div> -->


<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><b>Login in</b></h4>
      </div>
      <div class="modal-body">
        	<div class="">
	      		<div class="form-group">
			    	<label for="username">username</label>
			    	<input type="email" class="form-control" id="loginusername" placeholder="username">
			  	</div>
				<div class="form-group">
				    <label for="password">Password</label>
				    <input type="password" class="form-control" id="loginpassword" placeholder="Password">
				</div>
	   		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/pages/team.html.erb
<div class="center">
	<h1>Welcome to the Teams page</h1>
	</br>
	</br>
	<h3><b> About the Developer</b></h3>
	<p>The application is developed by <b>Adarsh Jayakumar</b> a current master student in computer science from northern illinois university</p>
	<p>He has been successful in developing application that are userfriendly and responsive that follows latest technologies</p>
</div>

app/views/pins/_form.html.erb
  <%= form_for @pin, html: {multipart: true} do |f| %>
    <% if @pin.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

        <ul>
        <% @pin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="col-sm-8">
      <div class="form-horizontal">
        <div class="form-group">
          <div class="field">
            <%= f.label :image , class: "col-sm-3 control-label" %>
            <div class="col-sm-5"><%= f.file_field :image , class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="field">
            <%= f.label :description , class: "col-sm-3 control-label" %>
            <div class="col-sm-5"><%= f.text_field :description , class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="actions">
            <div class="col-sm-3"></div>
            <div class="col-sm-5">
            <%= f.submit class: "btn btn-danger" %>
            </div>
          </div>
        </div>  
      </div>
     
  <% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>
	<div class="form-group">
		<div class="col-sm-3"></div>
		<div class="col-sm-5">
			<%= link_to 'Show', @pin %> |
			<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' if !user_signed_in? %>
<div id="pins" class="transitions-enabled">
	<% @pins.each do |pin| %>
		<div class="box panel panel-default">
	    	
	    	<%= link_to image_tag(pin.image.url), pin,  class: "index-image" %>
	    	
	    	<div class="panel-body">
	    	<strong><%= pin.description %></strong>
	    	<p style="font-size: 9px;"><%= pin.user.email if pin.user %></p>
	    	
	    	</div>
	    </div>
	<% end %>
</div>
<%= will_paginate @posts, class: "pagination-sm" , renderer: BootstrapPagination::Rails  %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>
	<div class="form-group">
		<div class="col-sm-3"></div>
		<div class="col-sm-5">
			<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>

app/views/pins/show.html.erb
<div class="col-sm-8">
	<%= link_to 'Back', pins_path , class: "btn btn-danger btn-sm" %><br>
		<div class="panel panel-default">
			<div class="panel-heading center">
				<!-- <img src="<%=@pin.image.url%>" width="300px" height="300px"> -->
				<%= image_tag @pin.image.url, class: "medium-image" %>
			</div>
			<div class="panel-body">
				<div>
					<p>
				  	<strong>Description:</strong>
				  	<%= @pin.description %>
					</p>
				</div>
				<div>
					<strong><%= @pin.user.email %></strong>
				</div>
				<div>
					<% if @pin.user == current_user %>
					<%= link_to 'Edit', edit_pin_path(@pin) , class: "btn btn-info btn-sm" %>
					<%= link_to raw('<span class="glyphicon glyphicon-trash" aria-hidden="true">'), @pin, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger btn-sm"%>
					<% end %>
				</div>
			</div>	
		</div>
</div>